name: Publish VS Code Extension

on:
  push:
    tags:
      - "v*"

jobs:
  publish-extension:
    runs-on: ubuntu-latest

    concurrency:
      group: publish-extension
      cancel-in-progress: true

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Build Extension
        run: npm run package

      #- name: Run Tests # Optional: Uncomment if you have tests to run before publishing
      #  run: npm test

      - name: Install VSCE
        run: npm install -g @vscode/vsce

      - name: Publish Extension
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: vsce publish --pat $VSCE_PAT
